version: '2'
services:

  rabbit:
    restart: always
    image: rabbitmq:3.6.0-management
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  backend:
    driver: bridge