version: '2'
services:

  rabbit:
    restart: always
    image: rabbitmq:3.6.0-management
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  discovery:
    restart: always
    image: tdc/discovery
    expose:
      - 8761
    ports:
      - 8761:8761
    depends_on:
      - rabbit
      - configuration
    networks:
      - backend

  configuration:
    restart: always
    image: tdc/configuration
    expose:
      - 8001
    ports:
      - 8001:8001
    depends_on:
      - rabbit
    networks:
      - backend

  products:
    restart: always
    image: tdc/products
    expose:
      - 9001
    ports:
      - 9001:9001
    depends_on:
      - discovery
      - configuration
    networks:
      - backend

networks:
  backend:
    driver: bridge