---
spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/claudioed/tdc-2016-files
          searchPaths: config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

server:
  port: 8001

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/claudioed/tdc-2016-files
          searchPaths: config
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG


eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

server:
  port: 8001